<div id="angebot" class="angebot">
    <h1>Unsere Angebote</h1>
    <div class="content">
        <div class="container">
            <div class="text">
                <div id="quality" class="icon">
                    <p class="head">Qualität</p>
                    <div class="underline"></div>
                </div>
                <p>Sie bekommen von uns immer frische und gute qualität</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div id="advice" class="icon">
                    <p class="head">Beratung</p>
                    <div class="underline"></div>
                </div>
                <p>Immer Top beratung durch erfahrenes Personal</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div id="happy" class="icon">
                    <p class="head">Kundenzufriedenheit</p>
                    <div class="underline"></div>
                </div>
                <p>Wir garantieren ihnen 100% kudenzufriedenheit</p>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container">
            <div class="text">
                <div id="grave" class="icon">
                    <p class="head">Grabpflege</p>
                    <div class="underline"></div>
                </div>
                <p>wir kümmern uns um die gräber ihrer verstorben</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div id="wedding" class="icon">
                    <p class="head">Hochzeiten</p>
                    <div class="underline"></div>
                </div>
                <p>Sie brauchen blumenschmuck für autos oder räume wir sind die richtigen!</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div id="scenery" class="icon">
                    <p class="head">Landschaftpflege</p>
                    <div class="underline"></div>
                </div>
                <p>sie Brauchen hilfe bei ihren gärten? kein problem melden sie sich</p>
            </div>
        </div>
    </div>
</div>