<div class="angebot">
    <h1>Unsere Angebote</h1>
    <h2>Wir versprechen ihnen:</h2>
    <div class="content">
        <div class="container">
            <div class="text">
                <div class="icon">icon</div>
                <p class="head">Hello world</p>
                <p>test Text zu testen des textes</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div class="icon">icon</div>
                <p class="head">Hello world</p>
                <p>test Text zu testen des textes</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div class="icon">icon</div>
                <p class="head">Hello world</p>
                <p>test Text zu testen des textes</p>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container">
            <div class="text">
                <div class="icon">icon</div>
                <p class="head">Hello world</p>
                <p>test Text zu testen des textes</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div class="icon">icon</div>
                <p class="head">Hello world</p>
                <p>test Text zu testen des textes</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div class="icon">icon</div>
                <p class="head">Hello world</p>
                <p>test Text zu testen des textes</p>
            </div>
        </div>
    </div>
</div>