<div id="angebot" class="angebot">
    <h1>Unsere Angebote</h1>
    <h2>Wir versprechen ihnen:</h2>
    <div class="content">
        <div class="container">
            <div class="text">
                <div id="quality" class="icon"></div>
                <p class="head">Qualität</p>
                <p>Immer Exelente qualität zu fairen Preien</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div id="advice" class="icon"></div>
                <p class="head">Top-Beratung</p>
                <p>Immer Top beratung durch erfahrenes Personal</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div id="happy" class="icon"></div>
                <p class="head">Kundenzufriedenheit</p>
                <p>Wir garantieren ihnen 100% kudenzufriedenheit</p>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container">
            <div class="text">
                <div id="grave" class="icon"></div>
                <p class="head">Grabpflege</p>
                <p>wir kümmern uns um die gräber ihrer verstorben</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div id="wedding" class="icon"></div>
                <p class="head">Hochzeiten</p>
                <p>Sie brauchen blumenschmuck für autos oder räume wir sind die richtigen!</p>
            </div>
        </div>
        <div class="container">
            <div class="text">
                <div id="scenery" class="icon"></div>
                <p class="head">Landschaft-Pflege</p>
                <p>sie Brauchen hilfe bei ihren gärten? kein problem melden sie sich</p>
            </div>
        </div>
    </div>
</div>