<div id="galary" class="bilder-galary">
    <h1>Bilder Galery</h1>
    <div class="slider">
        <p>hier sehen sie einer unser schnappschüsse</p>
        <div class="btn-next"></div>
        <div class="btn-back"></div>
        <div class="slider-content">
            <div class="wrapper">
                <div class="container">
                    <div class="picture show" id="pic-1">bild 1</div>
                    <div class="picture" id="pic-2">bild 2</div>
                    <div class="picture" id="pic-3">bild 3</div>
                    <div class="picture" id="pic-4">bild 4</div>
                </div>
            </div>
        </div>
    </div>
</div>