<div id="galary" class="bilder-galary">
    <div class="slider">
        <div class="btn-next"></div>
        <div class="btn-back"></div>
        <div class="slider-content">
            <div class="wrapper">
                <div class="container">
                    <div class="picture show" id="pic-0">
                        <div class="text-box">
                        <h2>Unsere Öffnungszeiten</h2>
                            <p class="anschrift">
                                <div class="tag">MO-FR</div>
                                <div class="uhrzeit">8:00 - 12:30 <br> 14:00 -18:00</div>
                                <div class="tag">SA</div>
                                <div class="uhrzeit"> 8:00 - 13:30</div>
                                <br>
                                <div class="small">Sonntags: Nur auf Vorbestellung, Abholung möglich</div>
                                <div class="tag">Tel.</div>
                                <div class="uhrzeit">07665/2310</div>
                            </p>
                        </div>
                    </div>
                    <div class="picture" id="pic-1">bild 2</div>
                    <div class="picture" id="pic-2">bild 3</div>
                    <div class="picture" id="pic-3">bild 4</div>
                    <div class="picture" id="pic-4">bild 5</div>
                </div>
            </div>
        </div>
    </div>
</div>