<div id="kalender" class="Kalender">
    <h1>kalenderberreich</h1>
    <div class="KalenderButtonNext" id="next"></div>
    <div class="KalenderButtonLast" id="last"></div>
    <p class="month"></p>
</div>
<div class="wrapper">
    <div class="kalenderbackground"></div>
    <div class="kalenderberreich"></div>
</div>

<?php if(parse_url($this->serverUrl(true), PHP_URL_PATH) == '/kalenderberreich') : ?>
	<button class="saveBtn">Termin Eintragen</button>
<?php endif ?>


