<?php

    $this->form->setAttribute('action', '/');
    $this->form->prepare();

?>
<div id="kontakt" class="kontakt">
    <h1>Kontakte</h1>
    <div class="text">
        <p>
            haben sie anregungn oder vorschläge?<br>
            wünsche oder Verbesserungen?<br>
            kritik oder beschwerden?<br>
            <br><br>
            wir freuen uns über ihre nachrichten
        </p>
    </div>
    <div class="formular">
        <form class="formular-berreich" action="" method="POST">
            <div class="wrapper">
                <?php echo $this->formRow($this->form->get('name')); ?>
            </div>
            <div class="email-field">
                <?php echo $this->formRow($this->form->get('email')); ?>
            </div>
            <div class="wrapper">
                <?php echo $this->formRow($this->form->get('betreff')); ?>
            </div>
            <div class="textarea">
                <?php echo $this->formRow($this->form->get('beschreibung')); ?>
            </div>
            <?php echo $this->formRow($this->form->get('abschicken')); ?>
        </form>
        <div class="text-box">
            <h2>unsere kontaktdaten</h2>
            <p class="anschrift">
                öffnungszeiten vom .... bis ....<br>
                telefonnummer 07696/1337<br>
                hochdorferstraße 7a<br>
                79232 march-hugstetten<br>
            </p>
        </div>
    </div>
</div>