<?php

    $this->form->setAttribute('action', '/');
    $this->form->prepare();

?>
<div id="kontakt" class="kontakt">
    <h1>Kontakt</h1>
    <div class="formular">
        <form class="formular-berreich" action="" method="POST">
            <div class="wrapper">
                <?php echo $this->formRow($this->form->get('name')); ?>
            </div>
            <div class="email-field">
                <?php echo $this->formRow($this->form->get('email')); ?>
            </div>
            <div class="wrapper">
                <?php echo $this->formRow($this->form->get('betreff')); ?>
            </div>
            <div class="textarea">
                <?php echo $this->formRow($this->form->get('beschreibung')); ?>
            </div>
            <?php echo $this->formRow($this->form->get('abschicken')); ?>
        </form>
        <div class="text-box">
            <h2>unsere Öffnungszeiten</h2>
            <p class="anschrift">
                Montag-Freitag 8:00 - 13:00
                & 14:00 -18:00<br>
                Samstag 8:00 - 13:00<br>
                telefonnummer 07696/1337<br>
                Telefax 015222452258255<br>
                email info@kremp.de<br>
                hochdorferstraße 7a
                79232 march-hugstetten
            </p>
        </div>
    </div>
</div>