<div class="kontakt">
    <h1>Kontakte</h1>
    <div class="text">
        <p>
            haben sie anregungn oder vorschläge?<br>
            wünsche oder Verbesserungen?<br>
            kritik oder beschwerden?<br>
            <br><br>
            wir freuen uns über ihre nachrichten
        </p>
    </div>
    <div class="formular">
        <input type="text" class="input-box" placeholder="name">
    </div>
</div>