<?php if($_POST['plant'] == 'ahorn'): ?>
    <h1>Ahorn</h1>
    <div class="text">
        <p>Der ahonr ist ein echt cooles blatt</p>
        <p>Der ahonr ist ein echt cooles blatt</p>
    </div>
<?php elseif($_POST['plant'] == 'bergholunder'): ?>
    <h1>Bergholunder</h1>
    <div class="text">
        <p>Der Bergholunder ist ein echt cooles blatt</p>
        <p>Der Bergholunder ist ein echt cooles blatt</p>
    </div>
<?php elseif($_POST['plant'] == 'jasmin'): ?>
    <h1>Jasmin</h1>
    <div class="text">
        <p>Der Jasmin ist ein echt cooles blatt</p>
        <p>Der Jasmin ist ein echt cooles blatt</p>
    </div>
<?php elseif($_POST['plant'] == 'grausche'): ?>
    <h1>grausche</h1>
    <div class="text">
        <p>Der grausche ist ein echt cooles blatt</p>
        <p>Der grausche ist ein echt cooles blatt</p>
    </div>
<?php elseif($_POST['plant'] == 'palmbaum'): ?>
    <h1>palmbaum</h1>
    <div class="text">
        <p>Der palmbaum ist ein echt cooles blatt</p>
        <p>Der palmbaum ist ein echt cooles blatt</p>
    </div>
<?php endif ?>
