<?php if($_POST['plant'] == 'ahorn'): ?>
    <h1>Ahorn</h1>
    <div class="text">
        <p>Der ahonr ist ein echt cooles blatt</p>
        <p>Der ahonr ist ein echt cooles blatt</p>
    </div>
<?php elseif($_POST['plant'] == 'bergholunder'): ?>
    <h1>Bergholunder</h1>
    <div class="text">
        <p>
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
        </p>
        <p>
        Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
        </p>
    </div>
<?php elseif($_POST['plant'] == 'jasmin'): ?>
    <h1>Jasmin</h1>
    <div class="text">
        <p>Der Jasmin ist ein echt cooles blatt</p>
        <p>Der Jasmin ist ein echt cooles blatt</p>
    </div>
<?php elseif($_POST['plant'] == 'grausche'): ?>
    <h1>grausche</h1>
    <div class="text">
        <p>Der grausche ist ein echt cooles blatt</p>
        <p>Der grausche ist ein echt cooles blatt</p>
    </div>
<?php elseif($_POST['plant'] == 'palmbaum'): ?>
    <h1>palmbaum</h1>
    <div class="text">
        <p>Der palmbaum ist ein echt cooles blatt</p>
        <p>Der palmbaum ist ein echt cooles blatt</p>
    </div>
<?php endif ?>


