        <div class="text-box">
            <h2>Öffnungszeiten</h2>
            <p class="anschrift">
                Montag-Freitag 8:00 - 13:00
                & 14:00 -18:00<br>
                Samstag 8:00 - 13:00<br>
                telefonnummer 07696/1337<br>
                Telefax 015222452258255<br>
                email info@kremp.de<br>
                hochdorferstraße 7a
                79232 march-hugstetten
            </p>
        </div>