<div class="verkauf">
    <h1>Verkauf</h1>
    <h2>Hier sehen sie einiger unsere Plfanzen</h2>
    <div class="content">
        <p>welche anforderungen soll ihre pflanze erfüllen?</p>
        <button class="brix-btn">Winterhart</button>
        <button class="brix-btn">Pflegeleicht</button>
        <button class="brix-btn">wenig Licht</button>
        <button class="brix-btn">wenig wasser</button>
    </div>
    <div class="row">
        <div class="portfolio">
            <div class="name">testtesttesttesttesttest</div>
        </div>
        <div class="portfolio">testtesttesttesttesttest</div>
        <div class="portfolio">testtesttesttesttesttest</div>
        <div class="portfolio">testtesttesttesttesttest</div>
        <div class="portfolio">testtesttesttesttesttest</div>
        <div class="portfolio">testtesttesttesttesttest</div>
    </div>
    <div class="row">
        <div class="portfolio">testtesttesttesttesttest</div>
        <div class="portfolio">testtesttesttesttesttest</div>
        <div class="portfolio">testtesttesttesttesttest</div>
        <div class="portfolio">testtesttesttesttesttest</div>
        <div class="portfolio">testtesttesttesttesttest</div>
        <div class="portfolio">testtesttesttesttesttest</div>
    </div>
</div>