<div id="verkauf" class="verkauf">
    <h1>Verkauf</h1>
    <h2>Hier sehen sie einiger unsere Plfanzen</h2>
    <div class="contentVerkauf">
        <button class="brix-btn" id="winterhart">Winterhart</button>
        <button class="brix-btn" id="pflegeleicht">Pflegeleicht</button>
        <button class="brix-btn" id="wenig_licht">wenig Licht</button>
        <button class="brix-btn" id="wenig_wasser">wenig Wasser</button>
        <button class="brix-btn" id="alle">Alle</button>
    </div>
    <div class="wrapper">
        <div class="row">
            <div class="portfolio winterhart" id="ahorn">
                <img src="<?php echo $this->basePath('../img/ahorn-2-gross.jpg') ?>" alt="1337" height="100%"width="100%">
                <div class="name">
                    <h3>Ahorn</h3>
                    <p>lateinisch Acer<p>
                </div>
            </div>
            <div class="portfolio wenig_licht" id="grausche">
                    <img src="<?php echo $this->basePath('../img/osterglocke-7632.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Grauesche</h3>
                    <p>Lateinisch: Fraxinus pennsylvanica</p>
                </div>
            </div>
            <div class="portfolio wenig_wasser" id="bergholunder">
                    <img src="<?php echo $this->basePath('../img/osterglocke-7632.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Bergholunder</h3>
                    <p>Lateinisch: Sambucus racemosa</p>
                </div>
            </div>
            <div class="portfolio pflegeleicht" id="jasmin">
                    <img src="<?php echo $this->basePath('../img/feature3.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Falscher jasmin</h3>
                    <p>Lateinisch: Philadelphus coronarius</p>
                </div>
            </div>
            <div class="portfolio winterhart" id="palmbaum">
                    <img src="<?php echo $this->basePath('../img/ahorn-2-gross.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Palmbaum</h3>
                    <p>Lateinisch: Chamaerops humilis</p>
                </div>
            </div>
            <div class="portfolio winterhart" id="ahorn">
                    <img src="<?php echo $this->basePath('../img/ahorn-2-gross.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Ahorn</h3>
                    <p>lateinisch Acer</p>
                </div>
            </div>
            <div class="portfolio wenig_licht" id="grausche">
                    <img src="<?php echo $this->basePath('../img/osterglocke-7632.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Grauesche</h3>
                    <p>Lateinisch: Fraxinus pennsylvanica</p>
                </div>
            </div>
            <div class="portfolio wenig_wasser" id="bergholunder">
                    <img src="<?php echo $this->basePath('../img/osterglocke-7632.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Bergholunder</h3>
                    <p>Lateinisch: Sambucus racemosa</p>
                </div>
            </div>
            <div class="portfolio pflegeleicht" id="jasmin">
                    <img src="<?php echo $this->basePath('../img/feature3.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Falscher jasmin</h3>
                    <p>Lateinisch: Philadelphus coronarius</p>
                </div>
            </div>
            <div class="portfolio winterhart" id="palmbaum">
                    <img src="<?php echo $this->basePath('../img/ahorn-2-gross.jpg') ?>" alt="1337" height="100%" width="100%">
                <div class="name">
                    <h3>Palmbaum</h3>
                    <p>Lateinisch: Chamaerops humilis</p>
                </div>
            </div>
        </div>
    </div>
</div>