<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('../css/aplication.css'))?>
    <script type="text/javascript" src="/../js/brix/jquery.js"></script>
    <script type="text/javascript" src="/../js/brix/scripts.js"></script>
</head>
<body>
<div class="navi">
    <div class="logo">
        <a href="/"><img src="<?php echo $this->basePath('../img/logo.png') ?>"></a>
    </div>
    <ul>
        <li><a href="#galary">Bilder-Galerie</a></li>
        <li><a href="#angebot">Angebote</a></li>
        <li><a href="#verkauf">Verkauf</a></li>
        <li><a href="#kalender">Kalender</a></li>
        <li><a href="#kontakt">Kontakt</a></li>
    </ul>
</div>
<div class="background">
    <div class="container">
        <div class="text-box">
            <h2>Öffnungszeiten</h2>
            <p class="anschrift">
                Montag-Freitag 8:00 - 13:00
                & 14:00 -18:00<br>
                Samstag 8:00 - 13:00<br>
                telefonnummer 07696/1337<br>
                Telefax 015222452258255<br>
                email info@kremp.de<br>
                hochdorferstraße 7a
                79232 march-hugstetten
            </p>
        </div>
        <?php echo $this->content; ?>
    </div>
</div>
<div class="layer">
    <div class="content-wrapper">
        <div class="close-layer"></div>
        <div class="layer-content"></div>
    </div>
</div>
<!-- formular layer for kalender -->
<div class="formularLayer">
    <div class="content-wrapper">
        <div class="close-layer"></div>
        <div class="layer-content"></div>
    </div>
</div>
<div class="footer">
    <ul>
        <li><a href="/impressum">Impressum</a></li>
    </ul>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
